// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq6qJoKGJtu4jT8_uDSsMlIRdEhkRngvI',
    appId: '1:704426176494:web:bf3c0e313c84d6932168ff',
    messagingSenderId: '704426176494',
    projectId: 'jobee-24',
    authDomain: 'jobee-24.firebaseapp.com',
    storageBucket: 'jobee-24.appspot.com',
    measurementId: 'G-WN3QDKDKXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmLxvqmuX53kcdwNtrYkrX8Hq04eUNSk',
    appId: '1:704426176494:android:090186e736964c632168ff',
    messagingSenderId: '704426176494',
    projectId: 'jobee-24',
    storageBucket: 'jobee-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQzDqwQJKBjlzfWYI7tRRlDPcjVWEODcQ',
    appId: '1:704426176494:ios:af3c90eae3c8bbb82168ff',
    messagingSenderId: '704426176494',
    projectId: 'jobee-24',
    storageBucket: 'jobee-24.appspot.com',
    iosBundleId: 'com.example.jobee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQzDqwQJKBjlzfWYI7tRRlDPcjVWEODcQ',
    appId: '1:704426176494:ios:c5dce1c89022c08d2168ff',
    messagingSenderId: '704426176494',
    projectId: 'jobee-24',
    storageBucket: 'jobee-24.appspot.com',
    iosBundleId: 'com.example.jobee.RunnerTests',
  );
}
